volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  postgres:
    image: docker.io/postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'
