# Generated by Django 5.2.7 on 2025-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigenerationsession',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error code for categorizing failures', max_length=50),
        ),
        migrations.AlterField(
            model_name='aigenerationsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Detailed error message if generation failed'),
        ),
    ]
