# Generated by Django 5.2.7 on 2025-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aigenerationsession_error_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='creation_method',
            field=models.CharField(choices=[('ai_full', 'AI Generated'), ('ai_edited', 'AI Generated (Edited)'),
                                            ('manual', 'Manually Created')], help_text='How this flashcard was created',
                                   max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='ai_review_state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='What this AI-generated flashcard review state is (empty for non-AI-generated flashcards)'),
        ),
    ]
